// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkXSl1Hn1Q4XNhVcNdmWlF7vQYReUWdU',
    appId: '1:1095203145542:web:69452623ce1b7bbd0a0747',
    messagingSenderId: '1095203145542',
    projectId: 'simplelogin-cc829',
    authDomain: 'simplelogin-cc829.firebaseapp.com',
    storageBucket: 'simplelogin-cc829.appspot.com',
    measurementId: 'G-W3T70GTDKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNpbBR_F8ORJ1JCgc3LCFMBtvfCn2wVQ',
    appId: '1:1095203145542:android:78c71e8801273bf40a0747',
    messagingSenderId: '1095203145542',
    projectId: 'simplelogin-cc829',
    storageBucket: 'simplelogin-cc829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgBpI9Us1MZjE6avzxHuyWF8DYthQOEw',
    appId: '1:1095203145542:ios:ac2b25d1e28fd7ee0a0747',
    messagingSenderId: '1095203145542',
    projectId: 'simplelogin-cc829',
    storageBucket: 'simplelogin-cc829.appspot.com',
    androidClientId: '1095203145542-2612hgm0eq06ct51bfis64njt4ctflgv.apps.googleusercontent.com',
    iosClientId: '1095203145542-mq07stpapsi4us1a4srumbjahkm3h612.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleScanner',
  );
}
